import { ArrowRight, ChevronRight } from 'lucide-react';
const items=[
 {name:'Salford Central',code:'M3',growth:'+28.4%',liq:'High Liquidity',image:'photo-1519501025264-65ba15a82390'},
 {name:'Digbeth',code:'B5',growth:'+24.7%',liq:'High Liquidity',image:'photo-1486406146926-c627a92ad1ab'},
 {name:'Leeds South Bank',code:'LS10',growth:'+22.1%',liq:'High Liquidity',image:'photo-1513635269975-59663e0ac1ad'},
 {name:'Sunderland City Centre',code:'SR1',growth:'+20.1%',liq:'Medium Liquidity',image:'photo-1518005020951-eccb494ad742'},
 {name:'Milton Keynes Central',code:'MK9',growth:'+19.8%',liq:'Medium Liquidity',image:'photo-1480714378408-67cf0d13bc1b'}
];
export default function MicroMarketsSection(){return <section id="micro-markets" className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-extrabold tracking-tight">Top emerging micro-markets this month</h2><a href="#markets" className="inline-flex items-center gap-1 text-sm font-bold text-brand hover:text-violet-800">View all <ChevronRight size={16}/></a></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">{items.map((m,i)=><a href="#markets" key={m.name} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-soft"><div className="relative h-32 overflow-hidden"><img className="h-full w-full object-cover transition duration-500 group-hover:scale-105" src={`https://images.unsplash.com/${m.image}?auto=format&fit=crop&w=700&q=80`} alt="UK urban neighbourhood"/><span className="absolute left-2 top-2 grid h-7 w-7 place-items-center rounded-lg bg-brand text-xs font-extrabold text-white">{i+1}</span></div><div className="p-3"><h3 className="text-sm font-extrabold text-slate-800">{m.name}</h3><p className="text-xs text-slate-400">{m.code}</p><div className="mt-2 flex items-center justify-between text-xs"><b className="text-emerald-600">{m.growth}</b><span className="font-semibold text-emerald-600">● High</span></div><div className="mt-0.5 flex justify-between text-[11px] text-slate-400"><span>Growth Outlook</span><span>Rental Pressure</span></div><div className="mt-3 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${m.liq.startsWith('High')?'bg-violet-100 text-brand':'bg-amber-50 text-amber-700'}`}>{m.liq}</span><ArrowRight size={15} className="text-brand"/></div></div></a>)}</div></section>}
