import { ArrowRight, Building2, MapPin } from 'lucide-react';
import Card from '../ui/Card';

const markets=[
 {name:'London',region:'Greater London',count:'4,993',areas:'33',image:'photo-1513635269975-59663e0ac1ad'},
 {name:'Liverpool',region:'Liverpool City Region',count:'1,003',areas:'6',image:'photo-1519501025264-65ba15a82390'},
 {name:'Leeds',region:'West Yorkshire',count:'1,404',areas:'5',image:'photo-1486406146926-c627a92ad1ab'},
 {name:'Manchester',region:'Greater Manchester',count:'1,702',areas:'10',image:'photo-1480714378408-67cf0d13bc1b'},
 {name:'Newcastle',region:'North East',count:'1,257',areas:'7',image:'photo-1518005020951-eccb494ad742'}
];
export default function MarketsSection(){return <section id="markets" className="mx-auto w-full max-w-[1440px] px-page-gutter pb-0 pt-section-y sm:px-8 xl:px-[63px]"><div className="mb-5 flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-[19px] font-extrabold leading-7 text-[#26233b]">Explore by Market</h2><a href="#markets" className="inline-flex items-center gap-1 text-[10px] font-bold text-[#5d2bef]">View all markets <ArrowRight size={11}/></a></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">{markets.map(m=><Card key={m.name} href="#micro-markets" variant="market" className="min-h-[205px]"><div className="h-[76px] overflow-hidden"><img src={`https://images.unsplash.com/${m.image}?auto=format&fit=crop&w=700&q=80`} alt={`${m.name} city skyline`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="flex-1 p-3 pb-[14px]"><h3 className="text-[12px] font-extrabold text-[#26233b]">{m.name}</h3><p className="text-[9px] leading-[14px] text-[#777180]">{m.region}</p><div className="mt-3 space-y-1 text-[9px] leading-[14px] text-slate-500"><p className="flex items-center gap-1"><MapPin size={10} className="text-[#5d2bef]"/>{m.count} micro-markets</p><p className="flex items-center gap-1"><Building2 size={10} className="text-[#5d2bef]"/>{m.areas} local areas</p></div><span className="mt-2 inline-flex items-center gap-1 text-[9px] font-bold text-[#5d2bef]">Explore market <ArrowRight size={11}/></span></div></Card>)}</div></section>}
